Initialization
PWrInSpace/turbo-octo-chainsaw pull request #3
Opened 2024-02-24 12:48 UTC by AlaiveCYA

Dodana funkcja inicjalizująca całą libke, bez głównej pętli i tx_interrupt, rx_interrupt

2024-02-24 20:22 UTC, JSiuda1 commented on ESP-IDF-Subordinate/main/file.c
Proszę zastąp magic numbery :magic_wand:

2024-02-24 20:23 UTC, JSiuda1 commented on ESP-IDF-Subordinate/main/file.c
> +    if(init_struct->tx_nack_timeout_ms > 60000){
Tutaj raczej chcemy ustawić ponad 60 sekund, bo cały lot wraz z opadaniem na spadochronie trwa kilka minut.

2024-02-24 20:25 UTC, JSiuda1 commented on ESP-IDF-Subordinate/main/file.c
> +    if(init_struct->tx_nack_timeout_ms > 60000){
A teraz myślę że w sumie możemy zahardkodować ten czas. Natomiast checki nadal bym zostawił i zapisywał to w tej strukturze. Kwestia tylko że będzie przypisywana z jakiegoś #define a nie ze struktury konfiguracyjnej.

2024-02-24 20:28 UTC, JSiuda1 commented on ESP-IDF-Subordinate/main/file.c
> +    if (transmit_periods->init_ms == 0 || transmit_periods->idle_ms == 0 || transmit_periods->armed_ms == 0 ||
Widzę że zdedcydowaliśmy się na strukture, a chyba jednak lepiej by było zmienić to na tabilcę tych czasów, a w enumie stany. To sprawdzanie trzeba będzie zmienić na pętle, ale później w przypadku zmian stanów, zmieniamy tylko enum i tablicę, a tutaj będzie się sprawdzać autoamtycznie w pętli.
```
enum {
INIT_MS = 0,
IDLE_MS
...
ENUM_MAX
};

transmit_periods[ENUM_MAX]
```

2024-02-24 20:29 UTC, JSiuda1 commented on ESP-IDF-Subordinate/main/file.c
> +        sub_struct.rx_data = xQueueCreate(10, sizeof(uint32_t));
Sprawdź czy kolejka została poprawnie stworzona :heavy_check_mark:

2024-02-24 20:29 UTC, JSiuda1 commented on ESP-IDF-Subordinate/main/file.c
> +    sub_struct.sleep_lock = xSemaphoreCreateMutex();
Sprawdź czy mutexy zostały poprawnie stworzone :white_check_mark:

2024-02-24 20:31 UTC, JSiuda1 requested changes
Uwzględnij komentarze i przenieś kod z folderu ESP-IDF-Subordinate, do głównego folderu projektu. Tak jak np tutaj:
https://github.com/PWrInSpace/MCB_Aurora

2024-02-25 10:01 UTC, AlaiveCYA commented
Wprowadziłem poprawki o które prosiłeś

2024-02-25 13:45 UTC, JSiuda1 commented on main/Kconfig.projbuild
Można usunąć ten plik

2024-02-25 13:46 UTC, JSiuda1 commented on main/component.mk
Ten w sumie też

2024-02-25 13:49 UTC, JSiuda1 commented on main/file.c
> +    if(TX_NACK_TIMEOUT_MS > MAX_TIMEOUT){
Można dodać dolne ograniczenie na 2 minuty

2024-02-25 13:50 UTC, JSiuda1 commented on main/file.c
> +        if(transmit_periods[i] > MAX_TIMEOUT){
I tutaj też dolne ograniczenie. Teraz może być z 10 ms, najwyżej później się zmieni

2024-02-25 13:51 UTC, JSiuda1 commented on main/file.h
> +uint16_t sub_transmit_periods[ENUM_MAX];
To chyba nie jest nigdzie używane później :t-rex:

2024-02-25 13:52 UTC, JSiuda1 requested changes
Drobnostki :space_invader:

2024-02-25 21:06 UTC, AlaiveCYA commented
wprowadzone zmiany

2024-02-26 18:53 UTC, JSiuda1 approved these changes

2024-02-26 19:22 UTC, merged